// Shared autocomplete data used by onboarding and the dashboard profile editor.
// COLLEGES covers the ~300 most-attended / best-known US universities and colleges,
// plus common short names / abbreviations so substring matching feels natural
// (e.g. typing "UT" surfaces "UT Austin", "UMich" surfaces "University of Michigan").

export const COLLEGES = [
  // Ivy League
  "Harvard University", "Yale University", "Princeton University", "Columbia University",
  "University of Pennsylvania", "Brown University", "Dartmouth College", "Cornell University",
  // Top private national universities
  "Stanford University", "Massachusetts Institute of Technology", "MIT",
  "California Institute of Technology", "Caltech", "University of Chicago", "UChicago",
  "Duke University", "Northwestern University", "Johns Hopkins University", "JHU",
  "Vanderbilt University", "Rice University", "Washington University in St. Louis", "WashU", "WUSTL",
  "University of Notre Dame", "Notre Dame", "Emory University", "Georgetown University",
  "Carnegie Mellon University", "CMU", "University of Southern California", "USC",
  "New York University", "NYU", "Tufts University", "Wake Forest University",
  "Boston College", "Boston University", "Brandeis University", "Case Western Reserve University",
  "Northeastern University", "Tulane University", "University of Rochester", "Lehigh University",
  "Rensselaer Polytechnic Institute", "RPI", "Worcester Polytechnic Institute", "WPI",
  "Stevens Institute of Technology", "Illinois Institute of Technology", "Rochester Institute of Technology", "RIT",
  "Southern Methodist University", "SMU", "Texas Christian University", "TCU",
  "Pepperdine University", "Baylor University", "Fordham University", "Syracuse University",
  "American University", "George Washington University", "Howard University", "Marquette University",
  "Creighton University", "Gonzaga University", "Santa Clara University", "Loyola Marymount University", "LMU",
  "Loyola University Chicago", "DePaul University", "Villanova University", "Providence College",
  "Seton Hall University", "Saint Louis University", "SLU", "University of Denver",
  "University of Miami", "Chapman University", "Elon University", "Yeshiva University",
  "Clark University", "Drexel University", "Hofstra University", "Duquesne University",
  "Catholic University of America", "Mercer University", "Belmont University", "Liberty University",
  // Top public national universities
  "University of California, Berkeley", "UC Berkeley", "Berkeley",
  "University of California, Los Angeles", "UCLA",
  "University of California, San Diego", "UCSD",
  "University of California, Davis", "UC Davis",
  "University of California, Irvine", "UC Irvine",
  "University of California, Santa Barbara", "UCSB",
  "University of California, Santa Cruz", "UC Santa Cruz",
  "University of California, Riverside", "UC Riverside",
  "University of California, Merced", "UC Merced",
  "University of Michigan", "UMich", "University of Michigan-Dearborn",
  "University of Virginia", "UVA",
  "University of North Carolina at Chapel Hill", "UNC", "UNC Chapel Hill",
  "University of Texas at Austin", "UT Austin", "UT",
  "University of Texas at Dallas", "UTD", "University of Texas at Arlington", "UTA",
  "University of Texas at San Antonio", "UTSA", "University of Texas at El Paso", "UTEP",
  "University of Florida", "UF", "Florida State University", "FSU",
  "University of Central Florida", "UCF", "University of South Florida", "USF",
  "Florida International University", "FIU",
  "University of Georgia", "UGA", "Georgia Institute of Technology", "Georgia Tech",
  "Georgia State University", "University of Wisconsin-Madison", "UW-Madison",
  "University of Illinois Urbana-Champaign", "UIUC", "University of Illinois Chicago", "UIC",
  "University of Washington", "UW", "University of Maryland, College Park", "UMD",
  "Ohio State University", "Ohio State", "Pennsylvania State University", "Penn State",
  "Purdue University", "Indiana University Bloomington", "Indiana University",
  "University of Minnesota", "University of Iowa", "Iowa State University", "Iowa State",
  "University of Wisconsin-Milwaukee", "Michigan State University", "Michigan State",
  "Rutgers University", "University of Pittsburgh", "Pitt",
  "University of Connecticut", "UConn", "University of Massachusetts Amherst", "UMass Amherst",
  "University of Colorado Boulder", "CU Boulder", "Colorado State University", "Colorado State",
  "University of Arizona", "Arizona State University", "ASU",
  "University of Utah", "University of Oregon", "Oregon State University",
  "University of Kansas", "Kansas State University", "University of Missouri", "Mizzou",
  "University of Nebraska-Lincoln", "University of Oklahoma", "OU", "Oklahoma State University",
  "University of Arkansas", "University of Alabama", "Auburn University", "Auburn",
  "University of Tennessee", "University of Kentucky", "University of Louisville",
  "Louisiana State University", "LSU", "University of Mississippi", "Ole Miss",
  "Mississippi State University", "University of South Carolina", "Clemson University",
  "North Carolina State University", "NC State", "NCSU", "East Carolina University",
  "Texas A&M University", "TAMU", "Texas Tech University", "Texas Tech", "TTU",
  "University of Houston", "University of North Texas", "UNT", "Texas State University", "Texas State",
  "Virginia Tech", "Virginia Commonwealth University", "VCU", "George Mason University",
  "University of Delaware", "University of New Hampshire", "University of Vermont",
  "University of Rhode Island", "University of Maine", "Stony Brook University",
  "University at Buffalo", "Binghamton University", "University of California, Hastings",
  "San Diego State University", "SDSU", "San Jose State University", "Cal Poly San Luis Obispo",
  "California Polytechnic State University", "Cal State Long Beach", "Cal State Fullerton",
  "San Francisco State University", "University of Nevada, Las Vegas", "UNLV",
  "University of Nevada, Reno", "University of Hawaii at Manoa", "University of Wyoming",
  "University of Montana", "Montana State University", "University of Idaho", "Boise State University",
  "University of New Mexico", "New Mexico State University", "West Virginia University", "WVU",
  "University of Cincinnati", "University of Dayton", "Miami University", "Kent State University",
  "Bowling Green State University", "University of Akron", "Wright State University",
  "Wayne State University", "Western Michigan University", "Central Michigan University",
  "Northern Illinois University", "Southern Illinois University", "Illinois State University",
  "University of Memphis", "Middle Tennessee State University", "University of Alabama at Birmingham", "UAB",
  "University of South Alabama", "Georgia Southern University", "Kennesaw State University",
  "University of North Carolina at Charlotte", "UNC Charlotte", "Appalachian State University",
  // Top liberal arts colleges
  "Williams College", "Amherst College", "Swarthmore College", "Swarthmore",
  "Pomona College", "Wellesley College", "Bowdoin College", "Carleton College",
  "Middlebury College", "Claremont McKenna College", "Claremont McKenna",
  "Davidson College", "Colgate University", "Hamilton College", "Vassar College", "Vassar",
  "Grinnell College", "Colby College", "Haverford College", "Smith College",
  "Washington and Lee University", "Washington and Lee", "Colorado College",
  "Wesleyan University", "Bates College", "Barnard College", "Harvey Mudd College", "Harvey Mudd",
  "Scripps College", "Pitzer College", "Bryn Mawr College", "Bryn Mawr", "Mount Holyoke College",
  "Macalester College", "Oberlin College", "Kenyon College", "Bucknell University",
  "Occidental College", "Trinity College", "Lafayette College", "Franklin & Marshall College",
  "Dickinson College", "Skidmore College", "Union College", "Sarah Lawrence College",
  "Reed College", "Whitman College", "Denison University", "DePauw University",
  "Sewanee: The University of the South", "Rhodes College", "Furman University",
  "Gettysburg College", "Connecticut College", "Wheaton College", "Bard College",
  "College of William & Mary", "William & Mary", "United States Military Academy", "West Point",
  "United States Naval Academy", "USNA", "United States Air Force Academy", "USAFA",
  "United States Coast Guard Academy", "Hendrix College", "Lake Forest College", "Hillsdale College",
  // Art, design, music & specialty
  "Rhode Island School of Design", "RISD", "Savannah College of Art and Design", "SCAD",
  "Pratt Institute", "Parsons School of Design", "School of the Art Institute of Chicago", "SAIC",
  "Ringling College of Art and Design", "California Institute of the Arts", "CalArts",
  "Berklee College of Music", "The Juilliard School", "Juilliard", "Fashion Institute of Technology", "FIT",
  "Cooper Union", "Babson College", "Babson", "Bentley University", "Embry-Riddle Aeronautical University",
  // Medical / health science schools commonly listed
  "Baylor College of Medicine", "UT Southwestern Medical Center", "UTSW",
  "McGovern Medical School", "Dell Medical School", "UT Health San Antonio", "UTHealth", "UTHealth SA",
  "University of Texas Medical Branch", "UTMB", "Icahn School of Medicine at Mount Sinai",
  "Weill Cornell Medicine", "Perelman School of Medicine", "Scripps Research",
  "UPenn Wharton", "UPenn Dental", "Harvard Business School", "Harvard Law", "Harvard Medical School",
  "Stanford Graduate School of Business", "Yale Law", "Columbia Business School", "NYU Stern", "NYU Law",
  "McCombs School of Business", "Kellogg School of Management", "Booth School of Business",
  "Duke Business", "Rice Business", "Northwestern Business", "UChicago Law", "UT Law",
  "Vanderbilt Law", "Lewis and Clark Law", "Fuller Theological Seminary",
  // Well-known international universities (sometimes attended by alumni)
  "University of Oxford", "Oxford", "University of Cambridge", "Cambridge",
  "London School of Economics", "LSE", "Imperial College London", "University College London", "UCL",
  "University of Toronto", "UToronto", "McGill University", "University of British Columbia", "UBC",
  "Leiden University", "Lund University", "Trinity College Dublin", "University of Edinburgh",
  "NYU Shanghai", "St. George's University", "St. Georges"
];

export const MAJORS = [
  "Computer Science", "Computer Engineering", "Electrical Engineering", "Mechanical Engineering",
  "Aerospace Engineering", "Chemical Engineering", "Civil Engineering", "Biomedical Engineering",
  "Industrial Engineering", "Software Engineering", "Data Science", "Business Administration",
  "Finance", "Accounting", "Marketing", "Management", "International Business",
  "Management Information Systems", "MIS", "Economics", "Econometrics", "Public Policy",
  "Political Science", "International Relations", "Government", "Psychology", "Clinical Psychology",
  "Biology", "Microbiology", "Neuroscience", "Chemistry", "Biochemistry", "Physics",
  "Mathematics", "Applied Mathematics", "Statistics", "Pre-Med", "Pre-Law", "Sociology",
  "Philosophy", "English", "English Literature", "History", "Art History", "Communications",
  "Journalism", "Nursing", "Public Health", "Environmental Science", "Geology", "Anthropology",
  "Linguistics", "Theater & Drama", "Film & Television", "Graphic Design", "Fine Arts",
  "Architecture", "Music", "Human Development", "Education"
];
